---
name: RSSHub
version: "latest"
slug: rsshub
description: Generate a RSS/Atom/JSON feed from anything
url: https://github.com/cuihaijun/hassio-addons
arch:
  - amd64
  - aarch64
image: diygod/rsshub
startup: services
boot: auto
init: false
ingress: true
ingress_port: 1200
panel_icon: mdi:newspaper-variant-multiple
panel_title: RSSHub
homeassistant: 2024.1.0
host_network: true
ports:
  1200/tcp: 1200
ports_description:
  1200/tcp: "RSSHub Web Interface"
watchdog: "tcp://[HOST]:[PORT:1200]"
map:
  - addon_config:rw
options:
  request_retry: 3
  request_timeout: 3000
  cache_expire: 3600
  cache_content_expire: 3600
  logger_level: info
schema:
  request_retry: int?
  request_timeout: int?
  cache_expire: int?
  cache_content_expire: int?
  logger_level: list(emerg|alert|crit|error|warning|notice|info|debug)?
