---
name: RSSHub
version: 2026.7.1
slug: rsshub
description: Generate a RSS/Atom/JSON feed from anything
url: https://github.com/cuihaijun/hassio-addons
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: mdi:newspaper-variant-multiple
panel_title: RSSHub
homeassistant: 2024.1.0
ports:
  1200/tcp: 1200
ports_description:
  1200/tcp: "Web Interface (HTTP or HTTPS when ssl is enabled)"
watchdog: "tcp://[HOST]:[PORT:1200]"
map:
  - addon_config:rw
  - all_addon_configs:rw
  - share:rw
  - ssl:rw
options:
  bind_address: 0.0.0.0:1200
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
schema:
  bind_address: str
  certfile: str
  keyfile: str
  ssl: bool
  request_retry: int?
  request_timeout: int?
  cache_expire: int?
  cache_content_expire: int?
  logger_level: list(emerg|alert|crit|error|warning|notice|info|debug)?
